package com.codingelab.validation.errors;
/*
 * 
 * @author Abdulrahman Abdulhamid Alsaedi
 * @since 23 September 2016
 * @version 1.0.1
 *
 */
public enum ErrorType {
	/*NO_ERROR,
	EMPTY_INPUT,
	
	HAS_LETTERS,
	REQUIRED_MORE_LETTERS,
	LETTERS_OUT_RANGE,
	LETTERS_IN_RANGE,
	
	HAS_NUMBERS,
	REQUIRED_MORE_NUMBERS,
	NUMBERS_OUT_RANGE,
	NUMBERS_IN_RANGE,
	
	HAS_SPECIAL_CHARACTERS,
	REQUIRED_MORE_SPECIAL_CHARACTERS,
	SPECIAL_CHARACTERS_OUT_RANGE,
	SPECIAL_CHARACTERS_IN_RANGE,
	
	HAS_WHITE_SPACES,
	WHITE_SPACES_OUT_RANGE,
	
	LENGTH_ABOVE_MAX_LIMIT,
	LENGTH_BELOW_MIN_LIMIT,
	LENGTH_BETWEEN,
	LENGTH_NOT_BETWEEN,
	LENGTH_NOT_EQUAL,
	LENGTH_NOT_ONE_OF;
	
	*/
}
